"""empty message

Revision ID: c365a6c1490
Revises: 510e7af6a53c
Create Date: 2014-07-28 08:31:47.119007

"""

# revision identifiers, used by Alembic.
revision = 'c365a6c1490'
down_revision = '510e7af6a53c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(length=255), nullable=True),
    sa.Column('teachers', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    ### end Alembic commands ###
